name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    name: Build (Windows)
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ./kristal
          repository: retake-crew/Brenotine
          ssh-key: ${{ secrets.T1 }}

      - name: Install Dependencies
        run: |
          pip install pe_tools

      - name: Download LÖVE
        run: |
          curl -L https://github.com/love2d/love/releases/download/11.5/love-11.5-win64.zip -o love.zip
          7z x love.zip
          rm love.zip

      - name: Build
        run: |
          python ./kristal/build.py --kristal ./kristal --love ./love-11.5-win64

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: ./output

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          tag_name: v1.0.0-WIN  # Example tag for your release
          release_name: Release v1.0.0-WIN  # Example release name
          body: |
            Release v1.0.0 WINDOWS EDITION
          draft: false
          prerelease: true

      - name: Upload Main Build
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./output/kristal-0.9.0-dev-win.zip
          asset_name: kristal-0.9.0-dev-win.zip
          asset_content_type: application/zip

      - name: Upload Example Mod
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./output/example-mod.zip
          asset_name: example-mod.zip
          asset_content_type: application/zip
